services:
  - type: web
    name: eleganttodos
    env: docker
    plan: free
    healthCheckPath: /api/todos
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false # This will be set manually in the Render dashboard
    dockerfilePath: ./Dockerfile